=== Minizbot2012/XEMIUtil/Schemas/xemi.json
{
  "$schema": "https://json-schema.org/draft-07/schema",
  "type": "object",
  "required": [
    "forms",
    "xemi"
  ],
  "description": "XEMI Objects contained within an array.",
  "properties": {
    "forms": {
      "type": "array",
      "description": "List of Form IDs / Base ID's or Editor IDs of the equivlant",
      "items": {
        "pattern": "[a-zA-Z\\_\\-0-9]*|[0-9A-Fa-f]{6}:.*\\.[Ee][Ss]\\.[PMLpml]$",
        "type": "string"
      }
    },
    "xemi": {
      "type": "string",
      "description": "Value of xemi (region) record",
      "pattern": "[a-zA-Z\\_\\-0-9]*|[0-9A-Fa-f]{6}:.*\\.[Ee][Ss]\\.[PMLpml]|null$"
    },
    "remove": {
      "type": "boolean",
      "description": "Remove the XEMI if xemi is \"null\""
    },
    "only_interior": {
      "type": "boolean",
      "description": "only modify interior references"
    },
    "forms_are_base": {
      "type": "boolean",
      "description": "forms are using base id's rather than reference id's"
    }
  }
}

=== Minizbot2012/XEMIUtil/example.json
{
  "$schema": "Schemas/xemi.json",
  "forms": [
    "0C1316:Update.esm",
    "0C49F5:Update.esm",
    "095C25:Update.esm",
    "0B829A:Update.esm",
    "0B8295:Update.esm",
    "0B8293:Update.esm",
    "0DDF94:Update.esm",
    "0C0EAC:Update.esm",
    "0695FD:Update.esm"
  ],
  "xemi": "null",
  "remove": true,
  "forms_are_base": false,
  "only_interior": false
}
